---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'checkmk_agent/pre_main.yml') }}"

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Configure Check_MK agent local facts
  template:
    src: 'etc/ansible/facts.d/checkmk_agent.fact.j2'
    dest: '/etc/ansible/facts.d/checkmk_agent.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: checkmk_agent__register_local_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: checkmk_agent__register_local_facts.changed

- name: Install Check_MK Agent
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  when: checkmk_agent|d()
  with_items: '{{ checkmk_agent__base_packages }}'

- name: Ensure the /etc/check_mk directory does exist
  file:
    dest: '/etc/check_mk'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- include: ssh_user.yml
  when: ((checkmk_agent|d() and 'ssh' in checkmk_agent) and
         (not checkmk_agent__ssh_user == "root"))

- include: xinetd.yml
  when: (checkmk_agent|d() and 'xinetd' in checkmk_agent)

- include: setup_plugins.yml
  tags: [ 'role::checkmk_agent:plugins' ]
  when: (checkmk_agent|d() and
         ansible_local|d() and ansible_local.checkmk_agent|d() and
         ansible_local.checkmk_agent.checkmk_agent__plugin_list|d())

- include: autojoin.yml
  tags: [ 'role::checkmk_agent:autojoin' ]
  when: (checkmk_agent|d() and
         checkmk_agent__autojoin|d())

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'checkmk_agent/post_main.yml') }}"
