---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'checkmk_agent/pre_main.yml') }}"

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Configure Check_MK agent local facts
  template:
    src: 'etc/ansible/facts.d/checkmk_agent.fact.j2'
    dest: '/etc/ansible/facts.d/checkmk_agent.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: checkmk_agent_register_local_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: checkmk_agent_register_local_facts.changed

- name: Install Check_MK Agent
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  when: checkmk_agent|d()
  with_items: '{{ checkmk__base_packages }}'

- name: Ensure the /etc/check_mk directory does exist
  file:
    dest: '/etc/check_mk'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Run tasks related to system user configuration
  include: system_user.yml

- name: Run tasks related to ssh user configuration
  include: ssh_user.yml
  when: ("ssh" in checkmk_agent|d([]))

- name: Run tasks related to xinetd configuration
  include: xinetd.yml
  when: ("xinetd" in checkmk_agent|d([]))

- name: Run tasks related to plugin setup
  include: setup_plugins.yml
  tags: [ 'role::checkmk_agent:plugins' ]
  when: (checkmk_agent|d() and
         ansible_local|d() and ansible_local.checkmk_agent|d() and
         ansible_local.checkmk_agent.checkmk_agent_plugin_list|d())

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'checkmk_agent/post_main.yml') }}"
