---

- name: Get Check_MK agent version
  shell: dpkg-query -W -f='${Version}\n' check-mk-agent 2>/dev/null | sed -e 's/^.*://' || true
  register: checkmk_agent__register_package_dpkg_version
  changed_when: False
  when: checkmk_agent__git_version == 'auto'
  tags: [ 'role::checkmk_agent:plugins:get' ]

- name: Clone Check_MK agent source
  git:
    repo: '{{ checkmk_agent__git_repo }}'
    dest: '{{ checkmk_agent__git_dest }}'
    version: '{{ (checkmk_agent__git_version_map["v" + checkmk_agent__register_package_dpkg_version.stdout.split("-")[0]]|d("v" + checkmk_agent__register_package_dpkg_version.stdout.split("-")[0])
                  if (checkmk_agent__git_version == "auto")
                  else (checkmk_agent__git_version_map[checkmk_agent__git_version]|d(checkmk_agent__git_version)))
                 if (checkmk_agent__git_version_unsigned_fallback|bool)
                 else ((checkmk_agent__git_version_map["v" + checkmk_agent__register_package_dpkg_version.stdout.split("-")[0]]
                   if (checkmk_agent__git_version == "auto")
                   else (checkmk_agent__git_version_map[checkmk_agent__git_version]))) }}'
    update: True
  tags: [ 'role::checkmk_agent:plugins:get' ]
  delegate_to: '{{ checkmk_agent__git_dest_host }}'
  become: '{{ False if (checkmk_agent__git_dest_host == "localhost") else True }}'
  run_once: True

- name: Install Check_MK plugins
  synchronize:
    src: '{{ checkmk_agent__git_dest }}/agents/plugins/{{ item }}'
    dest: '{{ checkmk_agent__plugin_path }}'
    checksum: True
    mode: 'push'
    verify_host: True
  with_items: '{{ checkmk_agent__combined_plugins }}'
  delegate_to: '{{ checkmk_agent__git_dest_host }}'

- name: Configure nginx_status plugin
  template:
    src: 'etc/check_mk/nginx_status.cfg.j2'
    dest: '/etc/check_mk/nginx_status.cfg'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: checkmk_agent__register_nginx_status_config
  when: ((checkmk_agent__plugin_nginx_servers != "automatic") and ("nginx_status" in checkmk_agent__combined_plugins))

- name: Ensure that nginx_status.cfg is absent for automatic detection
  file:
    path: '/etc/check_mk/nginx_status.cfg'
    state: 'absent'
  when: checkmk_agent__register_nginx_status_config is skipped
