---

- name: Get Check_MK agent version
  shell: dpkg-query -W -f='${Version}\n' check-mk-agent 2>/dev/null | sed -e 's/^.*://' || true
  register: checkmk_agent_register_package_dpkg_version
  changed_when: False
  when: checkmk_agent_git_version == 'auto'

- name: Clone Check_MK agent source
  git:
    repo: '{{ checkmk_agent_git_repo }}'
    dest: '{{ checkmk_agent_git_dest }}'
    version: '{{ "v" + checkmk_agent_register_package_dpkg_version.stdout.split("-")[0] if checkmk_agent_git_version == "auto" else checkmk_agent_git_version }}'
    update: True

- name: Install Check_MK plugins
  synchronize:
    src: '{{ checkmk_agent_git_dest }}/agents/plugins/{{ item }}'
    dest: '{{ checkmk_agent_plugin_path }}'
    checksum: True
    mode: 'push'
  with_items: ansible_local.checkmk_agent.checkmk_agent_plugin_list
  delegate_to: '{{ inventory_hostname }}'

- name: Configure nginx_status plugin
  template:
    src: 'etc/check_mk/nginx_status.cfg.j2'
    dest: '/etc/check_mk/nginx_status.cfg'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: (checkmk_agent_plugin_nginx_servers is defined and checkmk_agent_plugin_nginx_servers is not string)

- name: Ensure that nginx_status.cfg is absent for automatic detection
  file:
    path: '/etc/check_mk/nginx_status.cfg'
    state: 'absent'
  when: (checkmk_agent_plugin_nginx_servers|d("automatic") == "automatic")
