---

- name: Create Check_MK SSH user group
  group:
    name: '{{ checkmk_agent__ssh_group }}'
    system: 'yes'

- name: Create Check_MK SSH user
  user:
    name: '{{ checkmk_agent__ssh_user }}'
    group: '{{ checkmk_agent__ssh_group }}'
    groups: '{{ checkmk_agent__ssh_allow_group|d(omit) }}'
    system: 'yes'
    shell: '/bin/sh'
    home: '{{ checkmk_agent__user_home }}'
    createhome: 'yes'

- name: Enable sudo rule for Check_MK SSH user
  template:
    src: '{{ lookup("template_src", "etc/sudoers.d/check-mk-agent.j2") }}'
    dest: '/etc/sudoers.d/check-mk-agent'
    owner: 'root'
    group: 'root'
    mode: '0440'
