---

- name: Ensure the xinetd package is in the desired state
  package:
    name: 'xinetd'
    ## Might also be used for other things.
    # state: '{{ "present" if (checkmk_agent__deploy_state in ["present"]) else "absent" }}'

- name: Divert original /etc/xinetd.d/check_mk
  command: dpkg-divert --quiet --local --divert /etc/xinetd.d/check_mk.dpkg-divert --rename /etc/xinetd.d/check_mk
  args:
    creates: '/etc/xinetd.d/check_mk.dpkg-divert'

- name: Configure Check_MK service
  template:
    src: '{{ lookup("template_src", "etc/xinetd.d/check_mk.j2") }}'
    dest: '/etc/xinetd.d/check_mk'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart xinetd' ]
