---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Make sure check_mk configuration directory exists
  file:
    dest: '/etc/check_mk'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Configure Check_MK agent local facts
  template:
    src: 'etc/ansible/facts.d/checkmk_agent.fact.j2'
    dest: '/etc/ansible/facts.d/checkmk_agent.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: checkmk_agent__register_local_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: checkmk_agent__register_local_facts is changed
